version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/mebitek/sonarr/data:/config
      - /mnt/seagate/media/tvseries:/tv #optional
      - /home/mebitek/qbittorrent/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: always
