version: '3'

services:
  pihole:
    image: docker.io/pihole/pihole:latest
    container_name: pihole
    hostname: pihole.mebitek.local
    restart: always
    dns:
      - 127.0.0.1
      - 172.64.36.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8082:80/tcp"
    volumes:
      - '/home/pi/pi-hole/etc-pihole:/etc/pihole'
      - '/home/pi/pi-hole/etc-dnsmasq.d:/etc/dnsmasq.d'
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: ${PIHOLE_PASSWORD}
   
    networks:
      pihole:
       ipv4_address: 172.10.1.2


networks:                                                                       
   pihole:                                                                    
     external:                                                               
         true
