version: "3.4"

services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    build: .
    restart: always
    # volumes used to keep data persistent
    volumes:
      - /home/mebitek/lubelogger/data:/App/data
      - /home/mebitek/.aspnet/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    # expose port and/or use serving via traefik
    ports:
      - 8081:8080
    env_file:
      - .env

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "lubelogger"
      POSTGRES_PASSWORD: "lubepass"
      POSTGRES_DB: "lubelogger"
    volumes:
      - /home/mebitek/git/selfhosting/lubelogger/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /home/mebitek/lubelogger/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

volumes:
  data:
  keys:
  postgres:
