version: '3'

services:
  nextcloud:
    build: ./app
    image: nextcloud
    container_name: nextcloud
    restart: always
    networks: 
      - cloud
    ports:
      - 8081:80
    depends_on:
      - nextclouddb
      - redis
    volumes:
      - /home/mebitek/nextcloud/html:/var/www/html
      - /home/mebitek/nextcloud/custom_apps:/var/www/html/custom_apps
      - /home/mebitek/nextcloud/config:/var/www/html/config
      - /home/mebitek/nextcloud/data:/var/www/html/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=nextclouddb
      - REDIS_HOST=redis
    devices: # import drivers for HW accel
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    healthcheck:
      test: ["CMD-SHELL", "curl -Ss http://localhost/status.php | grep '\"installed\":true' || exit 1"]
      interval: 2m
      retries: 10
      start_period: 10m
      timeout: 5s

  nextclouddb:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks: 
      - cloud
    volumes:
      - /home/mebitek/nextcloud/nextclouddb:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${MYSQL_USER}
      
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /home/mebitek/nextcloud/redis:/data  
    networks: 
      - cloud

networks:
  cloud:
    name: cloud
    driver: bridge
