version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/mebitek/radarr/data:/config
      - /mnt/seagate/media/Film:/movies #optional
      - /srv/qbittorrent/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: always
