version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    restart: always
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/pi/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
      - /home/pi/homepage/images:/app/public/images
