version: "3.9"

services:
  watchtower:
    container_name: watchtower
    hostname: watchtower
    ports:
     - "3080:8080"
    environment:
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=watchtower@example.com
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=MyStrongSmtpLoginPassword
      #- WATCHTOWER_NOTIFICATION_EMAIL_FROM=watchtower@example.com
      #- WATCHTOWER_NOTIFICATION_EMAIL_TO=john.doe@example.com
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.google.com
      #- WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_SCHEDULE=0 0 6 * * * # requires a go cron syntax of 6 space-separated fields; see https://containrrr.dev/watchtower/arguments/#scheduling
      - WATCHTOWER_CLEANUP=true # remove unused images afterwards
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_HTTP_API_TOKEN=${TOKEN}
      - WATCHTOWER_NO_RESTART=false
      - WATCHTOWER_INCLUDE_RESTARTING=true
    image: containrrr/watchtower:latest
    labels:
      com.centurylinklabs.watchtower: true
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /
