version: "3.7"
services:
  collabora:
    image: collabora/code:latest
    restart: always
    container_name: collabora
    ports:
      - 9980:9980
    environment:
<<<<<<< HEAD
      - domain=nextcloud\.mebitek\.com|collabora\.mebitek\.com
      - server_name=collabora\.mebitek\.com
=======
      - domain=nextcloud.mebitek.com
      - server_name=collabora.mebitek.com
>>>>>>> 77594e4 (fix collabora)
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
      - SLEEPFORDEBUGGER=0

    volumes:
      - /etc/localtime:/etc/localtime
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - MKNOD
    privileged: true
