version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
#      - 8920:8920
    volumes:
      - /home/mebitek/jellyfin/config:/config
      - /home/mebitek/jellyfin/cache:/cache
      - /mnt/seagate/media:/media:rw
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
