version: "3"
services:
  app:
    image: dwaaan/hrconvert2-docker:latest
    user: "0:0"
    restart: always
    ports:
      - 8087:80
    volumes:
      - /home/mebitek/hrconvert2/config.php:/var/www/html/HRProprietary/HRConvert2/config.php
# uncomment the below line to expose temporary upload folder as a volume
#      - /home/mebitek/hrconvert2/files:/home/converter:rw
